services:
  db:
    image: postgres:12
    env_file: ${ENV_FILE:-.env}
    ports:
      - "5432:5432"

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 1s
      timeout: 5s
      retries: 10

  crud_api:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./crud_api:/src/crud_api
    depends_on:
      db:
        condition: service_healthy
    command: crud_api

  admin:
    build:
      context: .
    ports:
      - "8001:8501"
    volumes:
      - ./admin:/src/admin
    depends_on:
      - db
      - crud_api

    command: admin
