"""Добавлена уникальность названий

Revision ID: fb95fe336e36
Revises: dbc1913753bf
Create Date: 2025-03-15 20:33:05.286407

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "fb95fe336e36"
down_revision: str | None = "dbc1913753bf"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, "cargo", ["name"])
    op.create_unique_constraint(None, "city", ["name"])
    op.create_unique_constraint(None, "truck", ["name"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "truck", type_="unique")
    op.drop_constraint(None, "city", type_="unique")
    op.drop_constraint(None, "cargo", type_="unique")
    # ### end Alembic commands ###
