"""Добавлена уникальность названий

Revision ID: fb95fe336e36
Revises: dbc1913753bf
Create Date: 2025-03-15 20:33:05.286407

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fb95fe336e36'
down_revision: Union[str, None] = 'dbc1913753bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'cargo', ['name'])
    op.create_unique_constraint(None, 'city', ['name'])
    op.create_unique_constraint(None, 'truck', ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'truck', type_='unique')
    op.drop_constraint(None, 'city', type_='unique')
    op.drop_constraint(None, 'cargo', type_='unique')
    # ### end Alembic commands ###
